service: authorization-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: default
  region: eu-west-1
  stage: dev
  httpApi:
    cors: true

  environment:
    REGION: ${self:provider.region}

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
